"""fix tables relationship

Revision ID: 6f5f191794a2
Revises: 73b5da865d52
Create Date: 2025-08-28 00:18:08.846749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5f191794a2'
down_revision: Union[str, Sequence[str], None] = '73b5da865d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'])
    op.add_column('teachers', sa.Column('email', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'teachers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'email')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
