"""fix tables add  relationship

Revision ID: 73b5da865d52
Revises: 310f066d983f
Create Date: 2025-08-27 23:34:21.212910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73b5da865d52'
down_revision: Union[str, Sequence[str], None] = '310f066d983f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('grades', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('grades_subject_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'])
    op.drop_column('grades', 'subject')
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.add_column('grades', sa.Column('subject', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_subject_fkey'), 'grades', 'subjects', ['subject'], ['id'])
    op.drop_column('grades', 'subject_id')
    op.drop_column('grades', 'student_id')
    # ### end Alembic commands ###
